### ISSUE TITLE
Explain how to get sorted subarrays

### ISSUE THREAD

**Issue by xuan1905** [cambridgeltl/PairS#1]
The paper's Algorithm 1 mentioned two sorted subarrays as the input, but the code only requires a list of summaries as an input. 

Could you please explain where the (intermediate) subarrays appeared and how to sort them?

**Comment by williamLyh** [comment]
Think about the 'Merge sort' algorithm, where you divide the problem into sub-problems of 'merge two sorted sub-arrays'. This is a typical divide and conquer situation.
